#! /bin/zsh

# FIXME: Un-hardcode the architecture.

local mirrorlist='/etc/pacman.d/mirrorlist'
if [[ -n $1 ]] ; then
	mirrorlist=${1:A}
fi

<<EOF
[options]
Architecture = x86_64
CheckSpace
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = ${mirrorlist}

[extra]
Include = ${mirrorlist}

[community]
Include = ${mirrorlist}
EOF
