#! /bin/zsh

: require mcpp

local -a all_items
local -a items
local item
while read -rA items ; do
	for item in "${items[@]}" ; do
		[[ -n ${item} ]] || continue
		all_items+=("${item}")
	done
done < <(mcpp -e utf-8 -N -P -I- "${PKGLIST_DEFINES[@]}" < "$@")

print -rlo "${all_items[@]}"
